name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '15.x'
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install PyYAML jsonschema
#    - name: Validate yml files
#      run: |
#        python ./scripts/validate
    - name: Assemble yml files
      run: |
        mkdir -p public/resources && cd public/resources
        awk 1 `find ../../papers -name '*.yml' -not -path '**/types.yml' -not -path '**/tags.yml'` > allpapers.yml
        cp ../../papers/types.yml .
        cp ../../papers/tags.yml .
        cd ../..
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependency and build
      run: |
        npm install
        npm run build
    - name: Config Git
      run: |
        git config --global user.email "me@4f5da2.com"
        git config --global user.name "0x4f5da2"
    - name: Deploy
      run: |
        cd build
        git init
        git add --all
        git commit -m "Site Update:`TZ=':Asia/Shanghai' date +' %Y-%m-%d %H:%m:%S'`"
        git push --force https://${{ secrets.ACCESS_TOKEN }}@github.com/PaperReviews/PaperReviews.github.io.git master:page
